apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-sql
data:
  init.sql: |
    CREATE TABLE users (
      username TEXT PRIMARY KEY,
      password TEXT NOT NULL
    );

    INSERT INTO users (username, password) VALUES
      ('alice', '123'),
      ('bob', '123');

